knp_paginator:
    page_range: 5                     # nombre de pages visibles autour de la page courante
    default_options:
        page_name: page               # nom du paramètre dans l'URL (ex: ?page=2)
        sort_field_name: sort         # utilisé si tu veux trier les colonnes
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'   # template des liens de pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
